PROG=a86
SRCS= scan.c error.c init.c ins.c ps.c rel.c sdi.c sym.c
CFLAGS = -O \
	-Wno-incompatible-library-redeclaration \
	-Wno-implicit-int \
	-Wno-implicit-function-declaration \
	-Wno-return-type \
	-Wno-parentheses \
	-Wno-macro-redefined \
	-Wno-knr-promoted-parameter \

MAN1=

.include <bsd.prog.mk>
