PROG=cvt86

CFLAGS = -O -Wno-incompatible-library-redeclaration -Wno-implicit-int -Wno-implicit-function-declaration -Wno-return-type \
	-Wno-parentheses -Wno-dangling-else -Wno-macro-redefined -Wno-knr-promoted-parameter \
	-Wno-incompatible-pointer-types

MAN1=

.include <bsd.prog.mk>
