PROG=ld86

CFLAGS = -O \
	-Wno-incompatible-library-redeclaration \
	-Wno-implicit-int \
	-Wno-implicit-function-declaration \
	-Wno-return-type \
	-Wno-parentheses \
	-Wno-incompatible-pointer-types

MAN1=

.include <bsd.prog.mk>
